name: Patreon
version: ${project.version}
main: com.github.redoxplugins.patreon.Patreon
api-version: 1.16
authors: [MichielArkema, Olivio]
description: Fully integrate your minecraft server with patreon.
website: https://github.com/RedoxPlugins
